package com.example.task2

enum class Language(val code: String, val displayName: String) {
    ENGLISH("en", "EN"),
    RUSSIAN("ru", "RU"),
    BELARUSIAN("be", "BE")
}

data class AppStrings(
    val appName: String,
    val initialAmount: String,
    val annualRate: String,
    val termYears: String,
    val compounding: String,
    val monthly: String,
    val quarterly: String,
    val annually: String,
    val calculate: String,
    val finalAmount: String,
    val totalProfit: String,
    val capitalGrowth: String,
    val history: String,
    val clearHistory: String,
    val results: String,
    val year: String,
    val amount: String,
    val errorInvalidNumber: String,
    val errorNegativePrincipal: String,
    val errorNegativeRate: String,
    val errorYearsRange: String,
    val errorRateTooHigh: String,
    val errorPrincipalTooLarge: String,
    val noHistory: String,
    val currency: String,
    val settings: String,
    val enterAmount: String,
    val enterRate: String,
    val enterYears: String,
    val principal: String,
    val rate: String
)

val englishStrings = AppStrings(
    appName = "Financial Calculator",
    initialAmount = "Initial Amount",
    annualRate = "Annual Interest Rate (%)",
    termYears = "Term (Years)",
    compounding = "Compounding",
    monthly = "Monthly",
    quarterly = "Quarterly",
    annually = "Annually",
    calculate = "Calculate",
    finalAmount = "Final Amount",
    totalProfit = "Total Profit",
    capitalGrowth = "Capital Growth",
    history = "History",
    clearHistory = "Clear History",
    results = "Results",
    year = "Year",
    amount = "Amount",
    errorInvalidNumber = "Please enter a valid number",
    errorNegativePrincipal = "Principal cannot be negative",
    errorNegativeRate = "Interest rate cannot be negative",
    errorYearsRange = "Years must be between 1 and 100",
    errorRateTooHigh = "Interest rate is unrealistically high",
    errorPrincipalTooLarge = "Principal exceeds maximum allowed",
    noHistory = "No calculations yet",
    currency = "$",
    settings = "Settings",
    enterAmount = "Enter amount",
    enterRate = "Enter rate",
    enterYears = "Enter years",
    principal = "Principal",
    rate = "Rate"
)

val russianStrings = AppStrings(
    appName = "Финансовый калькулятор",
    initialAmount = "Начальная сумма",
    annualRate = "Годовая процентная ставка (%)",
    termYears = "Срок (лет)",
    compounding = "Капитализация",
    monthly = "Ежемесячно",
    quarterly = "Ежеквартально",
    annually = "Ежегодно",
    calculate = "Рассчитать",
    finalAmount = "Итоговая сумма",
    totalProfit = "Общая прибыль",
    capitalGrowth = "Рост капитала",
    history = "История",
    clearHistory = "Очистить историю",
    results = "Результаты",
    year = "Год",
    amount = "Сумма",
    errorInvalidNumber = "Введите корректное число",
    errorNegativePrincipal = "Начальная сумма не может быть отрицательной",
    errorNegativeRate = "Процентная ставка не может быть отрицательной",
    errorYearsRange = "Срок должен быть от 1 до 100 лет",
    errorRateTooHigh = "Процентная ставка нереалистично высокая",
    errorPrincipalTooLarge = "Начальная сумма превышает допустимый максимум",
    noHistory = "История расчётов пуста",
    currency = "₽",
    settings = "Настройки",
    enterAmount = "Введите сумму",
    enterRate = "Введите ставку",
    enterYears = "Введите срок",
    principal = "Сумма",
    rate = "Ставка"
)

val belarusianStrings = AppStrings(
    appName = "Фінансавы калькулятар",
    initialAmount = "Пачатковая сума",
    annualRate = "Гадавая працэнтная стаўка (%)",
    termYears = "Тэрмін (гады)",
    compounding = "Капіталізацыя",
    monthly = "Штомесячна",
    quarterly = "Штоквартальна",
    annually = "Штогадова",
    calculate = "Разлічыць",
    finalAmount = "Канчатковая сума",
    totalProfit = "Агульны прыбытак",
    capitalGrowth = "Рост капіталу",
    history = "Гісторыя",
    clearHistory = "Ачысціць гісторыю",
    results = "Вынікі",
    year = "Год",
    amount = "Сума",
    errorInvalidNumber = "Увядзіце карэктны лік",
    errorNegativePrincipal = "Пачатковая сума не можа быць адмоўнай",
    errorNegativeRate = "Працэнтная стаўка не можа быць адмоўнай",
    errorYearsRange = "Тэрмін павінен быць ад 1 да 100 гадоў",
    errorRateTooHigh = "Працэнтная стаўка нерэалістычна высокая",
    errorPrincipalTooLarge = "Пачатковая сума перавышае дапушчальны максімум",
    noHistory = "Гісторыя разлікаў пустая",
    currency = "Br",
    settings = "Налады",
    enterAmount = "Увядзіце суму",
    enterRate = "Увядзіце стаўку",
    enterYears = "Увядзіце тэрмін",
    principal = "Сума",
    rate = "Стаўка"
)

fun getStrings(language: Language): AppStrings = when (language) {
    Language.ENGLISH -> englishStrings
    Language.RUSSIAN -> russianStrings
    Language.BELARUSIAN -> belarusianStrings
}
